apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp
    spec:
      containers:
      - image: blacksheepjongwon/humastory:v1
        imagePullPolicy: IfNotPresent
        name: humastory2
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}

